### ISSUE TITLE
Vanilla Server Incompatibility - "Registry Object not present: betterlightning:medium_thunder"

### ISSUE THREAD

**Issue by CyberRat7** [Lyigh/Delayed_Thunder#1]
Happened randomly during a thunderstorm while playing on server
Here is the full crash log:
[crash-2024-09-07_17.24.18-client.txt](https://github.com/user-attachments/files/16918876/crash-2024-09-07_17.24.18-client.txt)

**Comment by katubug** [comment]
I've had the same crash but with short_thunder. I wonder if this is a client-only mod and that's why it crashes only on the server?

Edit: Oh, actually I don't have the file on the server. Maybe THAT's why?

**Comment by Lyigh** [comment]
Hi. Version 1.0 is required on both the server and the client, however clientside-only support is planned for 2.0

**Comment by Lyigh** [comment]
Learning more about the way forge handles sound registration, I don't plan to add clientside-only support for the time being. If there is another way of implementation I find, then I will return to this topic and fix this. Thank you.
