### ISSUE TITLE
[Suggestion] Lightning Strikes in Caves should get muffled

### ISSUE THREAD

**Issue by Nezzzer** [Lyigh/Delayed_Thunder#2]
Hello!
Quick heads up, I love this Mod you made, and wanted to say thank you for making such a Mod for Forge. 

Anyway, it came to my mind while playing that when Underground the Lightning Strikes actually don't get muffled which is kinda Disappointing since in real life you wouldn't hear a That Full Striking Sound of Thunder Underground, but a more muffled sound of that.
Except for that, The Mod works wonderful and is very Immersive in my Opinion.

For Technical Details (if needed):

I'm playing Version 1.20.1 on Forge 47.3.6

**Comment by Lyigh** [comment]
I agree with you. I will be working on this.

**Comment by Lyigh** [comment]
I have added a quick addition which is a configurable muffle below a y-level, which by default is set to y-level 30. This keeps the bolt sound, and should be friendly for lightning-summoning weapons being used underground. Let me know if there are any other methods of muffling that you believe should be considered, or if this interferes with immersion in- say- big ravines.

**Comment by Nezzzer** [comment]
Hmm tough one, I'm trying to learn to code myself, but I'm literary at the beginnings of beginnings with scripts and such, rather than Languages like (F.E: Java, C) so unfortunately no I can't provide myself maybe ask the Devs of Ambient Sounds? They seem to have Detection for Caves/Ravines since they add Background/Muffle Sound, maybe you can look at their Detection code or something. Speak with them, I'm certain they could help with this.
